using System.Collections.Generic;
using Game.Economy;

namespace AdvancedTPM.Systems
{
    public static class TPMDataDefinitions
    {
        public enum ResourceTaxArea { Industrial, Commercial, Office }

        public static readonly Dictionary<string, ResourceTaxArea> ResourceTaxAreaMap = new Dictionary<string, ResourceTaxArea>
        {
            ["grain"] = ResourceTaxArea.Industrial,
            ["vegetables"] = ResourceTaxArea.Industrial,
            ["cotton"] = ResourceTaxArea.Industrial,
            ["livestock"] = ResourceTaxArea.Industrial,
            ["fish"] = ResourceTaxArea.Industrial,
            ["wood"] = ResourceTaxArea.Industrial,
            ["ore"] = ResourceTaxArea.Industrial,
            ["stone"] = ResourceTaxArea.Industrial,
            ["coal"] = ResourceTaxArea.Industrial,
            ["oil"] = ResourceTaxArea.Industrial,
            ["food"] = ResourceTaxArea.Industrial,
            ["beverages"] = ResourceTaxArea.Industrial,
            ["conveniencefood"] = ResourceTaxArea.Industrial,
            ["textiles"] = ResourceTaxArea.Industrial,
            ["timber"] = ResourceTaxArea.Industrial,
            ["paper"] = ResourceTaxArea.Industrial,
            ["furniture"] = ResourceTaxArea.Industrial,
            ["metals"] = ResourceTaxArea.Industrial,
            ["steel"] = ResourceTaxArea.Industrial,
            ["minerals"] = ResourceTaxArea.Industrial,
            ["concrete"] = ResourceTaxArea.Industrial,
            ["machinery"] = ResourceTaxArea.Industrial,
            ["electronics"] = ResourceTaxArea.Industrial,
            ["vehicles"] = ResourceTaxArea.Industrial,
            ["petrochemicals"] = ResourceTaxArea.Industrial,
            ["plastics"] = ResourceTaxArea.Industrial,
            ["chemicals"] = ResourceTaxArea.Industrial,
            ["pharmaceuticals"] = ResourceTaxArea.Industrial,
            ["software"] = ResourceTaxArea.Office,
            ["telecom"] = ResourceTaxArea.Office,
            ["financial"] = ResourceTaxArea.Office,
            ["media"] = ResourceTaxArea.Office,
            ["lodging"] = ResourceTaxArea.Commercial,
            ["meals"] = ResourceTaxArea.Commercial,
            ["entertainment"] = ResourceTaxArea.Commercial,
            ["recreation"] = ResourceTaxArea.Commercial,
            ["c_food"] = ResourceTaxArea.Commercial,
            ["c_beverages"] = ResourceTaxArea.Commercial,
            ["c_conveniencefood"] = ResourceTaxArea.Commercial,
            ["c_textiles"] = ResourceTaxArea.Commercial,
            ["c_timber"] = ResourceTaxArea.Commercial,
            ["c_paper"] = ResourceTaxArea.Commercial,
            ["c_furniture"] = ResourceTaxArea.Commercial,
            ["c_metals"] = ResourceTaxArea.Commercial,
            ["c_steel"] = ResourceTaxArea.Commercial,
            ["c_minerals"] = ResourceTaxArea.Commercial,
            ["c_concrete"] = ResourceTaxArea.Commercial,
            ["c_machinery"] = ResourceTaxArea.Commercial,
            ["c_electronics"] = ResourceTaxArea.Commercial,
            ["c_vehicles"] = ResourceTaxArea.Commercial,
            ["c_petrochemicals"] = ResourceTaxArea.Commercial,
            ["c_plastics"] = ResourceTaxArea.Commercial,
            ["c_chemicals"] = ResourceTaxArea.Commercial,
            ["c_pharmaceuticals"] = ResourceTaxArea.Commercial,
        };

        public static readonly Dictionary<string, Resource> ResourceKeyToEnum = new Dictionary<string, Resource>
        {
            ["grain"]           = Resource.Grain,
            ["vegetables"]      = Resource.Vegetables,
            ["cotton"]          = Resource.Cotton,
            ["livestock"]       = Resource.Livestock,
            ["fish"]            = Resource.Fish,
            ["wood"]            = Resource.Wood,
            ["ore"]             = Resource.Ore,
            ["stone"]           = Resource.Stone,
            ["coal"]            = Resource.Coal,
            ["oil"]             = Resource.Oil,
            ["food"]            = Resource.Food,
            ["beverages"]       = Resource.Beverages,
            ["conveniencefood"] = Resource.ConvenienceFood,
            ["textiles"]        = Resource.Textiles,
            ["timber"]          = Resource.Timber,
            ["paper"]           = Resource.Paper,
            ["furniture"]       = Resource.Furniture,
            ["metals"]          = Resource.Metals,
            ["steel"]           = Resource.Steel,
            ["minerals"]        = Resource.Minerals,
            ["concrete"]        = Resource.Concrete,
            ["machinery"]       = Resource.Machinery,
            ["electronics"]     = Resource.Electronics,
            ["vehicles"]        = Resource.Vehicles,
            ["petrochemicals"]  = Resource.Petrochemicals,
            ["plastics"]        = Resource.Plastics,
            ["chemicals"]       = Resource.Chemicals,
            ["pharmaceuticals"] = Resource.Pharmaceuticals,
            ["software"]        = Resource.Software,
            ["telecom"]         = Resource.Telecom,
            ["financial"]       = Resource.Financial,
            ["media"]           = Resource.Media,
            ["lodging"]         = Resource.Lodging,
            ["meals"]           = Resource.Meals,
            ["entertainment"]   = Resource.Entertainment,
            ["recreation"]      = Resource.Recreation,
            ["c_food"]            = Resource.Food,
            ["c_beverages"]       = Resource.Beverages,
            ["c_conveniencefood"] = Resource.ConvenienceFood,
            ["c_textiles"]        = Resource.Textiles,
            ["c_timber"]          = Resource.Timber,
            ["c_paper"]           = Resource.Paper,
            ["c_furniture"]       = Resource.Furniture,
            ["c_metals"]          = Resource.Metals,
            ["c_steel"]           = Resource.Steel,
            ["c_minerals"]        = Resource.Minerals,
            ["c_concrete"]        = Resource.Concrete,
            ["c_machinery"]       = Resource.Machinery,
            ["c_electronics"]     = Resource.Electronics,
            ["c_vehicles"]        = Resource.Vehicles,
            ["c_petrochemicals"]  = Resource.Petrochemicals,
            ["c_plastics"]        = Resource.Plastics,
            ["c_chemicals"]       = Resource.Chemicals,
            ["c_pharmaceuticals"] = Resource.Pharmaceuticals,
        };
    }
}
